In [1]:
!kaggle datasets download -d najir0123/walmart-10k-sales-datasets

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/najir0123/walmart-10k-sales-datasets
License(s): MIT
Downloading walmart-10k-sales-datasets.zip to /content
100% 143k/143k [00:00<00:00, 72.4MB/s]

In [2]:
!unzip walmart-10k-sales-datasets.zip

Archive:  walmart-10k-sales-datasets.zip
  inflating: Walmart.csv

#### Data Exploration & Loading

In [1]:
# Importing Dependencies
import pandas as pd

# MySQL Toolkit
import pymysql    # Adapter
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# PostgreSQL
import psycopg2

In [2]:
df = pd.read_csv('Walmart.csv', encoding_errors='ignore')
df.shape

(10051, 11)

In [3]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [4]:
# Provide Descriptions of all Numerical Columns
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [5]:
# Provide all Information about the Dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [6]:
# Check all Duplicates
df.duplicated().sum()

np.int64(51)

In [7]:
# Drop all Duplicates
df.drop_duplicates(inplace=True)

In [8]:
# Check all Duplicates
df.duplicated().sum()

np.int64(0)

In [9]:
df.shape

(10000, 11)

In [10]:
# Check all Null Values
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [11]:
# Drop all Null Values
df.dropna(inplace=True)

In [12]:
# Verify all Null Values
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [13]:
df.shape

(9969, 11)

In [14]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price            str
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [15]:
df['unit_price'] = df['unit_price'].str.replace('$', '').astype(float)
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 934.6 KB

In [19]:
# Convert all the Column Names to Lowercase
df.columns = df.columns.str.lower()
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [20]:
df['total'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [21]:
df.shape

(9969, 12)

In [22]:
# Saves The Clean Data
df.to_csv('Walmart_Cleaned_Data.csv', index=False)

In [23]:
# MySQL Connection
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus('9938350479@Sarthak')

engine_MySQL = create_engine(
    f'mysql+pymysql://root:{password}@localhost:3306/walmart_sales'
)

try:
    with engine_MySQL.connect() as conn:
        print("Connection Successful!")
except Exception as e:
    print("Connection Failed!")
    print(e)

Connection Successful!

In [24]:
df.to_sql(name='walmart', con=engine_MySQL, if_exists='replace', index=False)

9969

In [25]:
# PostgreSQL Connection
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus('9938350479@Sarthak')

engine_PostgreSQL = create_engine(
    f'postgresql+psycopg2://postgres:{password}@localhost:5432/walmart_sales'
)

try:
    with engine_PostgreSQL.connect() as conn:
        print("Connection Successful!")
except Exception as e:
    print("Connection Failed!")
    print(e)

Connection Successful!

In [26]:
df.to_sql(name='walmart', con=engine_PostgreSQL, if_exists='replace', index=False)

969